export let locationDataProductionEN = {
  cities: [
    {
      name: 'Al Qattara Oasis',
      lat: ' 24.263893',
      lon: '55.749065',
      locations: [
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7523,
          name: 'Khalid Shafar',
          location: {
            lat: '24.261385',
            lon: '55.748286',
            city: 'Al Qattara Oasis',
            address: '',
            categories: [
              {
                type: 'Qattara',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7795,
              title: 'Sadu Red Carpet',
              name: null,
              slug: 'sadu-red-carpet',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/3tndcpkj/khalid-shafar-sadu-red-carpet-2025-image-courtesy-of-dct-abu-dhabi-1.jpg',
                    width: 1200,
                    height: 829,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7524,
          name: 'Rafael Lozano-Hemmer',
          location: {
            lat: '24.263893',
            lon: '55.749065',
            city: 'Al Qattara Oasis',
            address: '',
            categories: [
              {
                type: 'Qattara',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7564,
              title: 'Translation Stream',
              name: null,
              slug: 'translation-stream',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/nfgjz4zd/rafael-lozano-hemmer-translation-stream-2023-and-2025-image-courtesy-of-dct-abu-dhabi-5-1.jpg',
                    width: 1200,
                    height: 818,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7800,
          name: 'Rafael Lozano-Hemmer',
          location: {
            lat: '24.263397',
            lon: '55.749076',
            city: 'Al Qattara Oasis',
            address: '',
            categories: [
              {
                type: 'Qattara',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7794,
              title: 'Pulse Canopy',
              name: null,
              slug: 'pulse-canopy',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/qvycn2bj/rafael-lozano-hemmer-pulse-canopy-2025-image-courtesy-of-dct-abu-dhabi-2.jpg',
                    width: 1200,
                    height: 767,
                  },
                },
              ],
            },
          },
        },
      ],
      routes: [],
    },
    {
      name: 'Al Jimi Oasis',
      lat: '24.255809',
      lon: '55.747727',
      locations: [
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7522,
          name: 'Christian Brinkmann',
          location: {
            lat: '24.255087',
            lon: '55.747881',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [
              {
                type: 'Jimi',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7801,
          name: 'Ammar Al Attar',
          location: {
            lat: '24.255059',
            lon: '55.748084',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7788,
              title: 'Cycle Of Circles',
              name: null,
              slug: 'cycle-of-circles',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/bbyjmxgq/ammar-al-attar-cycle-of-circles-2025-image-courtesy-of-dct-abu-dhabi-1.jpg',
                    width: 1200,
                    height: 701,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7802,
          name: 'Abdalla Almulla',
          location: {
            lat: '24.2557656',
            lon: '55.7472143',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [
              {
                type: 'Jimi',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7789,
              title: 'Guiding Drapes',
              name: null,
              slug: 'guiding-drapes',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/hwvnqgfi/abdalla-almulla-guiding-drapes-2025-image-courtesy-of-dct-abu-dhabi-2-1.jpg',
                    width: 1200,
                    height: 729,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7803,
          name: 'Maitha Hamdan',
          location: {
            lat: '24.254851',
            lon: '55.747986',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [
              {
                type: 'Jimi',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7793,
              title: 'Breath of the Same Place',
              name: null,
              slug: 'breath-of-the-same-place',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/uajhj0hh/maitha-hamdan-breath-of-the-same-place-2025-image-courtesy-of-dct-abu-dhabi-4.jpg',
                    width: 1200,
                    height: 800,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'Parking',
          icon: 'https://resources.dct.gov.ae/publicart/media/iq2j13sy/parking.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/hzvelh04/parking_hover.svg',
          id: 8000,
          name: 'Parking',
          location: {
            lat: '24.263778',
            lon: '55.743063',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'Toilets',
          icon: 'https://resources.dct.gov.ae/publicart/media/f5rbxlnx/toilets.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/c11jt3rt/toilets_hover.svg',
          id: 8002,
          name: 'Toilets',
          location: {
            lat: '24.261059',
            lon: '55.748909',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'Toilets',
          icon: 'https://resources.dct.gov.ae/publicart/media/f5rbxlnx/toilets.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/c11jt3rt/toilets_hover.svg',
          id: 8003,
          name: 'Toilets',
          location: {
            lat: '24.260349517816223',
            lon: '55.74912218650539',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'Toilets',
          icon: 'https://resources.dct.gov.ae/publicart/media/f5rbxlnx/toilets.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/c11jt3rt/toilets_hover.svg',
          id: 8004,
          name: 'Toilets',
          location: {
            lat: '24.263253',
            lon: '55.749241',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'Toilets',
          icon: 'https://resources.dct.gov.ae/publicart/media/f5rbxlnx/toilets.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/c11jt3rt/toilets_hover.svg',
          id: 8005,
          name: 'Toilets',
          location: {
            lat: '24.256290',
            lon: '55.746062',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'Food & Beverage',
          icon: 'https://resources.dct.gov.ae/publicart/media/50sprjx1/food__beverages.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/dbtet2qc/food__beverages_hover.svg',
          id: 8007,
          name: 'Food & Beverage',
          location: {
            lat: '24.255226',
            lon: '55.748078',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'Food & Beverage',
          icon: 'https://resources.dct.gov.ae/publicart/media/50sprjx1/food__beverages.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/dbtet2qc/food__beverages_hover.svg',
          id: 8008,
          name: 'Food & Beverage',
          location: {
            lat: '24.255229',
            lon: '55.747907',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'Food & Beverage',
          icon: 'https://resources.dct.gov.ae/publicart/media/50sprjx1/food__beverages.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/dbtet2qc/food__beverages_hover.svg',
          id: 8009,
          name: 'Food & Beverage',
          location: {
            lat: '24.261204',
            lon: '55.748265',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'Food & Beverage',
          icon: 'https://resources.dct.gov.ae/publicart/media/50sprjx1/food__beverages.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/dbtet2qc/food__beverages_hover.svg',
          id: 8010,
          name: 'Food & Beverage',
          location: {
            lat: '24.263852',
            lon: '55.748773',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'Info Points',
          icon: 'https://resources.dct.gov.ae/publicart/media/fzkhyzl3/information.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/fvyekts3/information_hover.svg',
          id: 8011,
          name: 'Info point',
          location: {
            lat: '24.263697',
            lon: '55.748600',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'Buggy Pick-up Point',
          icon: 'https://resources.dct.gov.ae/publicart/media/ancj4xpz/pickup.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/kgdmb2t1/pickup-hover.svg',
          id: 8099,
          name: 'Buggy Pick-up Point',
          location: {
            lat: '24.263750',
            lon: '55.743056',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'Buggy Pick-up Point',
          icon: 'https://resources.dct.gov.ae/publicart/media/ancj4xpz/pickup.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/kgdmb2t1/pickup-hover.svg',
          id: 8100,
          name: 'Buggy Pick-up Point',
          location: {
            lat: '24.263972',
            lon: '55.746167',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'Buggy Pick-up Point',
          icon: 'https://resources.dct.gov.ae/publicart/media/ancj4xpz/pickup.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/kgdmb2t1/pickup-hover.svg',
          id: 8101,
          name: 'Buggy Pick-up Point',
          location: {
            lat: '24.260889',
            lon: '55.747722',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'Buggy Pick-up Point',
          icon: 'https://resources.dct.gov.ae/publicart/media/ancj4xpz/pickup.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/kgdmb2t1/pickup-hover.svg',
          id: 8102,
          name: 'Buggy Pick-up Point',
          location: {
            lat: '24.256778',
            lon: '55.749639',
            city: 'Al Jimi Oasis',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
      ],
      routes: [],
    },
    {
      name: 'Souq Al Mina',
      lat: '24.528419',
      lon: '54.363024',
      locations: [
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7521,
          name: 'KAWS',
          location: {
            lat: '24.528419',
            lon: ' 54.363024',
            city: 'Souq Al Mina',
            address: '',
            categories: [
              {
                type: 'Souq Al Mina',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7566,
              title: 'KAWS: Holiday Abu Dhabi',
              name: null,
              slug: 'holiday',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/guhj1c0j/compressed_kaws-holiday_-shanghai-at-the-north-bund-dock-shanghai.jpeg',
                    width: 1200,
                    height: 1500,
                  },
                },
              ],
            },
          },
        },
      ],
      routes: [],
    },
    {
      name: 'Jubail Island',
      lat: '24.536035',
      lon: '54.489263',
      locations: [
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7519,
          name: 'Shaikha Al Mazrou',
          location: {
            lat: '24.541526',
            lon: '54.495752',
            city: 'Jubail Island',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7567,
              title: 'Contingent Object',
              name: null,
              slug: 'contingent-object',
              images: [],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7781,
          name: 'Pamela Poh',
          location: {
            lat: '24.535294',
            lon: '54.493524',
            city: 'Jubail Island',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7776,
              title: 'Eden',
              name: null,
              slug: 'eden',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/wfikmt0f/compressed_path_1.jpeg',
                    width: 1200,
                    height: 675,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7784,
          name: 'DRIFT',
          location: {
            lat: '24.537003',
            lon: '54.491632',
            city: 'Jubail Island',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7778,
              title: 'Whispers',
              name: null,
              slug: 'whispers',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/inihcfnp/compressed_drift_whispers.png',
                    width: 617,
                    height: 343,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7804,
          name: 'DRIFT',
          location: {
            lat: '24.536035',
            lon: ' 54.489263',
            city: 'Jubail Island',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7786,
              title: 'Wind of Change',
              name: null,
              slug: 'wind-of-change',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/t0cjoeup/compressed_drift_windofchange.jpeg',
                    width: 1200,
                    height: 759,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7805,
          name: 'DRIFT',
          location: {
            lat: '24.536513',
            lon: '54.493589',
            city: 'Jubail Island',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7785,
              title: 'UNFOLD',
              name: null,
              slug: 'unfold',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/w4ejxqdv/compressed_drift_unfold.png',
                    width: 1112,
                    height: 496,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7806,
          name: 'Iregular',
          location: {
            lat: '24.536035',
            lon: '54.489263',
            city: 'Jubail Island',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7796,
              title: 'As Water Falls',
              name: null,
              slug: 'as-water-falls',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/m3uaub5b/compressed_awf_by_iregular_12_hd_credit-bruno-aiello-destombes.jpeg',
                    width: 1200,
                    height: 800,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7807,
          name: 'Iregular',
          location: {
            lat: '24.536035',
            lon: '54.489263',
            city: 'Jubail Island',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7798,
              title: 'Faces',
              name: null,
              slug: 'faces',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/bvzd0fdx/compressed_faces_adelaide_01_hd_credit_iregular.jpeg',
                    width: 1200,
                    height: 800,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7808,
          name: 'Iregular',
          location: {
            lat: '24.536035',
            lon: '54.489263',
            city: 'Jubail Island',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7797,
              title: 'Control No Control',
              name: null,
              slug: 'control-no-control',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/21gofccf/compressed_cnc_6_credit_iregular.jpeg',
                    width: 1200,
                    height: 800,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7809,
          name: 'Iregular',
          location: {
            lat: '24.536035',
            lon: '54.489263',
            city: 'Jubail Island',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7799,
              title: 'Fortunes',
              name: null,
              slug: 'fortunes',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/z2khr0n3/compressed_frt_03_hd_credit-iregular.jpeg',
                    width: 1200,
                    height: 800,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7810,
          name: 'Ezequiel Pini (Six N. Five)',
          location: {
            lat: '24.536261',
            lon: '54.494428',
            city: 'Jubail Island',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7787,
              title: 'Skyward',
              name: null,
              slug: 'skyward',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/xvndr3es/compressed_skyward.webp',
                    width: 1184,
                    height: 864,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7811,
          name: 'Encor Studio',
          location: {
            lat: '24.535766',
            lon: '54.492633',
            city: 'Jubail Island',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7791,
              title: 'Alcove Ltd',
              name: null,
              slug: 'alcove-ltd',
              images: [],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7812,
          name: 'Kirsten Berg',
          location: {
            lat: '24.535733',
            lon: '54.494082',
            city: 'Jubail Island',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7790,
              title: 'Compound Eye',
              name: null,
              slug: 'compound-eye',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/mt1edyrs/compressed_kirsten_compound-eye.jpeg',
                    width: 283,
                    height: 407,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7813,
          name: 'Lachlan Turczan',
          location: {
            lat: '24.536595',
            lon: '54.490422',
            city: 'Jubail Island',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7792,
              title: 'Gateway',
              name: null,
              slug: 'gateway',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/vcsb2jg5/compressed_whatsapp-image-2025-09-29-at-001438.jpeg',
                    width: 1200,
                    height: 1600,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'Artwork',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7814,
          name: 'Christian Brinkmann',
          location: {
            lat: '24.535920',
            lon: '54.491962',
            city: 'Jubail Island',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7819,
              title: 'Floral Resonance',
              name: null,
              slug: 'floral-resonance',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/ekqdre1a/christian-brinkmann-floral-resonance-2024-ongoing-image-courtesy-of-dct-abu-dhabi-1.jpg',
                    width: 1200,
                    height: 761,
                  },
                },
              ],
            },
          },
        },
      ],
      routes: [],
    },
  ],
  locationTypes: ['Artwork', 'Parking', 'Info Points', 'Prayer Room', 'Toilets', 'Food & Beverage', 'Buggy Pick-up Point'],
}

export let locationDataProductionAR = {
  cities: [
    {
      name: 'واحة القطارة',
      lat: ' 24.263893',
      lon: '55.749065',
      locations: [
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7523,
          name: 'خالد شعفار',
          location: {
            lat: '24.261385',
            lon: '55.748286',
            city: 'واحة القطارة',
            address: '',
            categories: [
              {
                type: 'Qattara',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7795,
              title: 'سجادة السدو الحمراء',
              name: null,
              slug: 'sadu-red-carpet',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/3tndcpkj/khalid-shafar-sadu-red-carpet-2025-image-courtesy-of-dct-abu-dhabi-1.jpg',
                    width: 1200,
                    height: 829,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7524,
          name: 'رافاييل لوزانو هيمر',
          location: {
            lat: '24.263893',
            lon: '55.749065',
            city: 'واحة القطارة',
            address: '',
            categories: [
              {
                type: 'Qattara',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7564,
              title: 'سيل القصائد العابرة ',
              name: null,
              slug: 'translation-stream',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/nfgjz4zd/rafael-lozano-hemmer-translation-stream-2023-and-2025-image-courtesy-of-dct-abu-dhabi-5-1.jpg',
                    width: 1200,
                    height: 818,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7800,
          name: 'رافاييل لوزانو هيمر',
          location: {
            lat: '24.263397',
            lon: '55.749076',
            city: 'واحة القطارة',
            address: '',
            categories: [
              {
                type: 'Qattara',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7794,
              title: 'نبضات من نور',
              name: null,
              slug: 'pulse-canopy',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/qvycn2bj/rafael-lozano-hemmer-pulse-canopy-2025-image-courtesy-of-dct-abu-dhabi-2.jpg',
                    width: 1200,
                    height: 767,
                  },
                },
              ],
            },
          },
        },
      ],
      routes: [],
    },
    {
      name: ' واحة الجيمي',
      lat: '24.255809',
      lon: '55.747727',
      locations: [
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7522,
          name: 'كريستيان برينكمان',
          location: {
            lat: '24.255087',
            lon: '55.747881',
            city: ' واحة الجيمي',
            address: '',
            categories: [
              {
                type: 'Jimi',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7801,
          name: 'عمّار العطار',
          location: {
            lat: '24.255059',
            lon: '55.748084',
            city: ' واحة الجيمي',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7788,
              title: 'مدارات',
              name: null,
              slug: 'cycle-of-circles',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/bbyjmxgq/ammar-al-attar-cycle-of-circles-2025-image-courtesy-of-dct-abu-dhabi-1.jpg',
                    width: 1200,
                    height: 701,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7802,
          name: 'عبدلله الملا',
          location: {
            lat: '24.2557656',
            lon: '55.7472143',
            city: ' واحة الجيمي',
            address: '',
            categories: [
              {
                type: 'Jimi',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7789,
              title: 'زها الدار',
              name: null,
              slug: 'guiding-drapes',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/hwvnqgfi/abdalla-almulla-guiding-drapes-2025-image-courtesy-of-dct-abu-dhabi-2-1.jpg',
                    width: 1200,
                    height: 729,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7803,
          name: 'ميثاء حمدان',
          location: {
            lat: '24.254851',
            lon: '55.747986',
            city: ' واحة الجيمي',
            address: '',
            categories: [
              {
                type: 'Jimi',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7793,
              title: 'نَفَس المكان/ نفس المكان ',
              name: null,
              slug: 'breath-of-the-same-place',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/uajhj0hh/maitha-hamdan-breath-of-the-same-place-2025-image-courtesy-of-dct-abu-dhabi-4.jpg',
                    width: 1200,
                    height: 800,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'موقف سيارات',
          icon: 'https://resources.dct.gov.ae/publicart/media/iq2j13sy/parking.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/hzvelh04/parking_hover.svg',
          id: 8000,
          name: 'موقف سيارات',
          location: {
            lat: '24.263778',
            lon: '55.743063',
            city: ' واحة الجيمي',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'الحمّامات',
          icon: 'https://resources.dct.gov.ae/publicart/media/f5rbxlnx/toilets.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/c11jt3rt/toilets_hover.svg',
          id: 8002,
          name: 'الحمّامات',
          location: {
            lat: '24.261059',
            lon: '55.748909',
            city: ' واحة الجيمي',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'الحمّامات',
          icon: 'https://resources.dct.gov.ae/publicart/media/f5rbxlnx/toilets.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/c11jt3rt/toilets_hover.svg',
          id: 8003,
          name: 'الحمّامات',
          location: {
            lat: '24.260349517816223',
            lon: '55.74912218650539',
            city: ' واحة الجيمي',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'الحمّامات',
          icon: 'https://resources.dct.gov.ae/publicart/media/f5rbxlnx/toilets.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/c11jt3rt/toilets_hover.svg',
          id: 8004,
          name: 'الحمّامات',
          location: {
            lat: '24.263253',
            lon: '55.749241',
            city: ' واحة الجيمي',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'الحمّامات',
          icon: 'https://resources.dct.gov.ae/publicart/media/f5rbxlnx/toilets.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/c11jt3rt/toilets_hover.svg',
          id: 8005,
          name: 'الحمّامات',
          location: {
            lat: '24.256290',
            lon: '55.746062',
            city: ' واحة الجيمي',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'المأكولات والمشروبات',
          icon: 'https://resources.dct.gov.ae/publicart/media/50sprjx1/food__beverages.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/dbtet2qc/food__beverages_hover.svg',
          id: 8007,
          name: 'المأكولات والمشروبات',
          location: {
            lat: '24.255226',
            lon: '55.748078',
            city: ' واحة الجيمي',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'المأكولات والمشروبات',
          icon: 'https://resources.dct.gov.ae/publicart/media/50sprjx1/food__beverages.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/dbtet2qc/food__beverages_hover.svg',
          id: 8008,
          name: 'المأكولات والمشروبات',
          location: {
            lat: '24.255229',
            lon: '55.747907',
            city: ' واحة الجيمي',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'المأكولات والمشروبات',
          icon: 'https://resources.dct.gov.ae/publicart/media/50sprjx1/food__beverages.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/dbtet2qc/food__beverages_hover.svg',
          id: 8009,
          name: 'المأكولات والمشروبات',
          location: {
            lat: '24.261204',
            lon: '55.748265',
            city: ' واحة الجيمي',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'المأكولات والمشروبات',
          icon: 'https://resources.dct.gov.ae/publicart/media/50sprjx1/food__beverages.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/dbtet2qc/food__beverages_hover.svg',
          id: 8010,
          name: 'المأكولات والمشروبات',
          location: {
            lat: '24.263852',
            lon: '55.748773',
            city: ' واحة الجيمي',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: 'نقطة المعلومات',
          icon: 'https://resources.dct.gov.ae/publicart/media/fzkhyzl3/information.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/fvyekts3/information_hover.svg',
          id: 8011,
          name: 'نقطة المعلومات',
          location: {
            lat: '24.263697',
            lon: '55.748600',
            city: ' واحة الجيمي',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: '\u200eنقطة ركوب عربات النقل',
          icon: 'https://resources.dct.gov.ae/publicart/media/ancj4xpz/pickup.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/kgdmb2t1/pickup-hover.svg',
          id: 8099,
          name: '\u200eنقطة ركوب عربات النقل',
          location: {
            lat: '24.263750',
            lon: '55.743056',
            city: ' واحة الجيمي',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: '\u200eنقطة ركوب عربات النقل',
          icon: 'https://resources.dct.gov.ae/publicart/media/ancj4xpz/pickup.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/kgdmb2t1/pickup-hover.svg',
          id: 8100,
          name: '\u200eنقطة ركوب عربات النقل',
          location: {
            lat: '24.263972',
            lon: '55.746167',
            city: ' واحة الجيمي',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: '\u200eنقطة ركوب عربات النقل',
          icon: 'https://resources.dct.gov.ae/publicart/media/ancj4xpz/pickup.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/kgdmb2t1/pickup-hover.svg',
          id: 8101,
          name: '\u200eنقطة ركوب عربات النقل',
          location: {
            lat: '24.260889',
            lon: '55.747722',
            city: ' واحة الجيمي',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
        {
          locationType: '\u200eنقطة ركوب عربات النقل',
          icon: 'https://resources.dct.gov.ae/publicart/media/ancj4xpz/pickup.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/kgdmb2t1/pickup-hover.svg',
          id: 8102,
          name: '\u200eنقطة ركوب عربات النقل',
          location: {
            lat: '24.256778',
            lon: '55.749639',
            city: ' واحة الجيمي',
            address: '',
            categories: [],
            description: '',
            card: [],
            appCard: [],
            artwork: null,
          },
        },
      ],
      routes: [],
    },
    {
      name: 'سوق الميناء',
      lat: '24.528419',
      lon: '54.363024',
      locations: [
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7521,
          name: 'كاوس',
          location: {
            lat: '24.528419',
            lon: ' 54.363024',
            city: 'سوق الميناء',
            address: '',
            categories: [
              {
                type: 'Souq Al Mina',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7566,
              title: 'كاوز: هوليداي أبوظبي',
              name: null,
              slug: 'holiday',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/guhj1c0j/compressed_kaws-holiday_-shanghai-at-the-north-bund-dock-shanghai.jpeg',
                    width: 1200,
                    height: 1500,
                  },
                },
              ],
            },
          },
        },
      ],
      routes: [],
    },
    {
      name: 'جزيرة الجبيل',
      lat: '24.536035',
      lon: '54.489263',
      locations: [
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7519,
          name: 'شيخة المزروع',
          location: {
            lat: '24.541526',
            lon: '54.495752',
            city: 'جزيرة الجبيل',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7567,
              title: 'النجم العابر: جوهرة هشّة من ملح الأرض',
              name: null,
              slug: 'contingent-object',
              images: [],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7781,
          name: 'باميلا بو',
          location: {
            lat: '24.535294',
            lon: '54.493524',
            city: 'جزيرة الجبيل',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7776,
              title: 'عدن',
              name: null,
              slug: 'eden',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/wfikmt0f/compressed_path_1.jpeg',
                    width: 1200,
                    height: 675,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7784,
          name: 'دريفت',
          location: {
            lat: '24.537003',
            lon: '54.491632',
            city: 'جزيرة الجبيل',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7778,
              title: 'همسات',
              name: null,
              slug: 'whispers',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/inihcfnp/compressed_drift_whispers.png',
                    width: 617,
                    height: 343,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7804,
          name: 'دريفت',
          location: {
            lat: '24.536035',
            lon: ' 54.489263',
            city: 'جزيرة الجبيل',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7786,
              title: 'رياح التغيير',
              name: null,
              slug: 'wind-of-change',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/t0cjoeup/compressed_drift_windofchange.jpeg',
                    width: 1200,
                    height: 759,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7805,
          name: 'دريفت',
          location: {
            lat: '24.536513',
            lon: '54.493589',
            city: 'جزيرة الجبيل',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7785,
              title: 'تجلّي',
              name: null,
              slug: 'unfold',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/w4ejxqdv/compressed_drift_unfold.png',
                    width: 1112,
                    height: 496,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7806,
          name: 'إيريغولر',
          location: {
            lat: '24.536035',
            lon: '54.489263',
            city: 'جزيرة الجبيل',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7796,
              title: 'حين يتدفّق الشلّال',
              name: null,
              slug: 'as-water-falls',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/m3uaub5b/compressed_awf_by_iregular_12_hd_credit-bruno-aiello-destombes.jpeg',
                    width: 1200,
                    height: 800,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7807,
          name: 'إيريغولر',
          location: {
            lat: '24.536035',
            lon: '54.489263',
            city: 'جزيرة الجبيل',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7798,
              title: 'وجوه ',
              name: null,
              slug: 'faces',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/bvzd0fdx/compressed_faces_adelaide_01_hd_credit_iregular.jpeg',
                    width: 1200,
                    height: 800,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7808,
          name: 'إيريغولر',
          location: {
            lat: '24.536035',
            lon: '54.489263',
            city: 'جزيرة الجبيل',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7797,
              title: 'خارج السيطرة',
              name: null,
              slug: 'control-no-control',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/21gofccf/compressed_cnc_6_credit_iregular.jpeg',
                    width: 1200,
                    height: 800,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7809,
          name: 'إيريغولر',
          location: {
            lat: '24.536035',
            lon: '54.489263',
            city: 'جزيرة الجبيل',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7799,
              title: 'أقدار',
              name: null,
              slug: 'fortunes',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/z2khr0n3/compressed_frt_03_hd_credit-iregular.jpeg',
                    width: 1200,
                    height: 800,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7810,
          name: 'إيزيكييل بيني',
          location: {
            lat: '24.536261',
            lon: '54.494428',
            city: 'جزيرة الجبيل',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7787,
              title: 'ممرّ إلى السماء',
              name: null,
              slug: 'skyward',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/xvndr3es/compressed_skyward.webp',
                    width: 1184,
                    height: 864,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7811,
          name: 'أنكور ستوديو',
          location: {
            lat: '24.535766',
            lon: '54.492633',
            city: 'جزيرة الجبيل',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7791,
              title: 'الكوّة',
              name: null,
              slug: 'alcove-ltd',
              images: [],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7812,
          name: 'كيرستن بيرغ',
          location: {
            lat: '24.535733',
            lon: '54.494082',
            city: 'جزيرة الجبيل',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7790,
              title: 'عيون متكررة',
              name: null,
              slug: 'compound-eye',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/mt1edyrs/compressed_kirsten_compound-eye.jpeg',
                    width: 283,
                    height: 407,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7813,
          name: 'لاكلان توركزان',
          location: {
            lat: '24.536595',
            lon: '54.490422',
            city: 'جزيرة الجبيل',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7792,
              title: 'المعبر',
              name: null,
              slug: 'gateway',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/vcsb2jg5/compressed_whatsapp-image-2025-09-29-at-001438.jpeg',
                    width: 1200,
                    height: 1600,
                  },
                },
              ],
            },
          },
        },
        {
          locationType: 'عمل فني',
          icon: 'https://resources.dct.gov.ae/publicart/media/qvdps41h/artworks.svg',
          hoverIcon: 'https://resources.dct.gov.ae/publicart/media/ztbfhvoj/artworks_hover.svg',
          id: 7814,
          name: 'كريستيان برينكمان',
          location: {
            lat: '24.535920',
            lon: '54.491962',
            city: 'جزيرة الجبيل',
            address: '',
            categories: [
              {
                type: 'Jubail Island',
              },
            ],
            description: '',
            card: [],
            appCard: [],
            artwork: {
              id: 7819,
              title: 'في متنفّس الزهور',
              name: null,
              slug: 'floral-resonance',
              images: [
                {
                  portrait: null,
                  landscape: null,
                  card: {
                    url: 'https://resources.dct.gov.ae/publicart/media/ekqdre1a/christian-brinkmann-floral-resonance-2024-ongoing-image-courtesy-of-dct-abu-dhabi-1.jpg',
                    width: 1200,
                    height: 761,
                  },
                },
              ],
            },
          },
        },
      ],
      routes: [],
    },
  ],
  locationTypes: ['عمل فني', 'موقف سيارات', 'نقطة المعلومات', 'Prayer Room', 'الحمّامات', 'المأكولات والمشروبات', '\u200eنقطة ركوب عربات النقل'],
}
