export const locationData = {
  cities: [
    {
      name: 'Al Jimi Oasis',
      lat: '24.255809',
      lon: '55.747727',
      locations: [
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5211,
          name: 'Ammar Al Attar',
          location: { lat: '24.255059', lon: '55.748084', city: 'Al Jimi Oasis', address: '', categories: [{ type: 'Jimi' }], description: '', card: [], appCard: [], artworks: [] },
        },
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5212,
          name: 'Christian Brinkmann',
          location: { lat: '24.255087,', lon: '55.747881', city: 'Al Jimi Oasis', address: '', categories: [{ type: 'Jimi' }], description: '', card: [], appCard: [], artworks: [] },
        },
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5213,
          name: 'Abdalla Al Mula',
          location: { lat: '24.2557656', lon: '55.7472143', city: 'Al Jimi Oasis', address: '', categories: [{ type: 'Jimi' }], description: '', card: [], appCard: [], artworks: [] },
        },
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5214,
          name: 'Maitha Hamdan',
          location: { lat: '24.254851', lon: '55.747986', city: 'Al Jimi Oasis', address: '', categories: [], description: '', card: [], appCard: [], artworks: [] },
        },
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5215,
          name: 'Maitha Hamdan 2 ',
          location: { lat: '24.255809', lon: '55.747727', city: 'Al Jimi Oasis', address: '', categories: [{ type: 'Jimi' }], description: '', card: [], appCard: [], artworks: [] },
        },
      ],
      routes: [],
    },
    {
      name: 'Souq Al Mina',
      lat: '24.263893',
      lon: '55.749065',
      locations: [
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5216,
          name: 'KAWS',
          location: { lat: '24.263893', lon: '55.749065', city: 'Souq Al Mina', address: '', categories: [{ type: 'Mina Zayed' }], description: '', card: [], appCard: [], artworks: [] },
        },
      ],
      routes: [],
    },
    {
      name: 'Jubail Island',
      lat: '24.536035',
      lon: '54.489263',
      locations: [
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5217,
          name: 'Pamela Poh',
          location: { lat: '24.5356746', lon: '54.491646', city: 'Jubail Island', address: '', categories: [{ type: 'Jubail Island' }], description: '', card: [], appCard: [], artworks: [] },
        },
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5218,
          name: 'Studio DRIFT',
          location: { lat: '24.5356746', lon: '54.491646', city: 'Jubail Island', address: '', categories: [{ type: 'Jubail Island' }], description: '', card: [], appCard: [], artworks: [] },
        },
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5219,
          name: 'Iregular',
          location: { lat: '24.5356746', lon: '54.491646', city: 'Jubail Island', address: '', categories: [{ type: 'Jubail Island' }], description: '', card: [], appCard: [], artworks: [] },
        },
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5220,
          name: 'Ezequiel Pini',
          location: { lat: '24.5356746', lon: '54.491646', city: 'Jubail Island', address: '', categories: [{ type: 'Jubail Island' }], description: '', card: [], appCard: [], artworks: [] },
        },
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5221,
          name: 'Christian Brinkmann',
          location: { lat: '24.5356746', lon: '54.491646', city: 'Jubail Island', address: '', categories: [{ type: 'Jubail Island' }], description: '', card: [], appCard: [], artworks: [] },
        },
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5222,
          name: 'Encor Studio',
          location: { lat: '24.5356746', lon: '54.491646', city: 'Jubail Island', address: '', categories: [{ type: 'Jubail Island' }], description: '', card: [], appCard: [], artworks: [] },
        },
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5223,
          name: 'Kirsten Berg',
          location: { lat: '24.5356746', lon: '54.491646', city: 'Jubail Island', address: '', categories: [{ type: 'Jubail Island' }], description: '', card: [], appCard: [], artworks: [] },
        },
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5224,
          name: 'Shaikha Al Mazrou',
          location: { lat: '24.5356746', lon: '54.491646', city: 'Jubail Island', address: '', categories: [{ type: 'Jubail Island' }], description: '', card: [], appCard: [], artworks: [] },
        },
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5225,
          name: 'Lachlan Turczan',
          location: { lat: '24.5356746', lon: '54.491646', city: 'Jubail Island', address: '', categories: [{ type: 'Jubail Island' }], description: '', card: [], appCard: [], artworks: [] },
        },
      ],
      routes: [],
    },
    {
      name: 'Al Qattara Oasis',
      lat: '24.263893',
      lon: '55.749065',
      locations: [
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5207,
          name: 'Rafael Lozano',
          location: {
            lat: '24.263893',
            lon: '55.749065',
            city: 'Al Qattara Oasis',
            address: '',
            categories: [{ type: 'Qattara' }],
            description: '',
            card: [],
            appCard: [],
            artworks: [
              {
                id: 3105,
                title: null,
                name: null,
                slug: 'pillars-that-dance-with-the-wind',
                images: [
                  {
                    portrait: { url: '/media/ududje13/portrait-768x1630-02.jpg', width: 0, height: 0 },
                    landscape: { url: '/media/unmd3cyz/landscape-3840x2000-02.jpg', width: 0, height: 0 },
                    card: { url: '/media/euxccbzu/card-2336x1669-02.jpg', width: 0, height: 0 },
                  },
                ],
              },
            ],
          },
        },
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5208,
          name: 'Rafael Lozano - Pulse Canopy',
          location: { lat: '24.263397', lon: '55.749076', city: 'Al Qattara Oasis', address: '', categories: [{ type: 'Qattara' }], description: '', card: [], appCard: [], artworks: [] },
        },
        {
          locationType: 'Artworks',
          icon: '/media/s1old13r/manar-star-01-primary.svg',
          id: 5210,
          name: 'Khalid Alshafar',
          location: { lat: '24.261385', lon: '55.748286', city: 'Al Qattara Oasis', address: '', categories: [{ type: 'Qattara' }], description: '', card: [], appCard: [], artworks: [] },
        },
      ],
      routes: [],
    },
  ],
}
